[theme]
base = "dark"
primaryColor = "#0070FF"
backgroundColor = "#05070A"
secondaryBackgroundColor = "#0B0E14"
textColor = "#E0E0E0"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
